### ISSUE TITLE
MARGIN = 2?

### ISSUE THREAD

**Issue by neilcharles** [MilesMcBain/slippymath#13] opened 2019-04-09 12:12 UTC
In this piece of raster_to_png()

`tile_raster@data@values <-
    sweep(tile_raster@data@values,
          MARGIN = 1,
          STATS = tile_raster@data@max,
          FUN = "/")`

Should MARGIN = 2? At the moment, it throws a warning for me if the number of rows in tile_raster@data@values doesn't divide by 3 (which is the length of tile_raster@data@max).

**Comment by daniel-j-miller** [comment] 2019-04-12 11:37
I've made a change to this function in a branch that gets rid of the need for the sweep function which means it will work on OSX. Not sure if this is of interest or not.

A very strange thing appears to be occurring with the RasterBrick objects in OSX, at least for me, where the tile_raster@data@values appears to be empty, causing sweep to fail. However the values are definitely in there. Let me know if this would be helpful.

**Comment by MilesMcBain** [comment] 2019-04-13 13:27
I think I have a fix for this although I never saw the warning you mentioned @neilcharles... was is the 'Quick access to digital elevation model data' section in the `geoviz` README?

@daniel-j-miller I don't know the full details but @mdsumner told me that `raster` sometimes elects to load the `@data` slot lazily from some temporary storage on disk. I suspect that's what's happening here. To be safe I'll materialise the data with `raster::as.array` before normalising it.

**Comment by MilesMcBain** [comment] 2019-04-13 13:42
I was able to find and reproduce the broken `geoviz` example image posted to Twitter. I don't have a MacOS machine handy though so I'll need to add a test I can run on r-hub before I close this. You can try the fix in meantime, it's pushed to master.

**Comment by mdsumner** [comment] 2019-04-13 14:15
Use the raster API ...

**Comment by daniel-j-miller** [comment] 2019-04-14 02:35
Yep your fix works for me, though took me a bit to realise geoviz wasn't actually using slippymath::raster_to_png anymore.

**Comment by mdsumner** [comment] 2019-04-14 02:49
Oh, you do now use `as.array` 👍👍 

I *did not understand* the use of sweep before, I guess I'd do this which might be faster:

```R
a <- raster::as.array(tile_raster)
a[] <- a / rep(tile_raster@data@max, each = raster::ncell(tile_raster))
```
(I'll see if there's a better way to get that max value). 

Also probably should check that `raster::nlayers(tile_raster)` is either 1, 3, or 4 - otherwise the error will come from png.

**Comment by neilcharles** [comment] 2019-04-17 08:40
@daniel-j-miller Yes, I put a quick fix in geoviz to use its own version of raster_to_png() but plan to go back to slippymath's when a fix hits CRAN.

@MilesMcBain Sounds like you already found the warning, but I think sweep() was cycling down the rows of tile_raster@data@values and warning if they weren't divisible by 3. They are in your uluru example so you don't get warned.

**Closed as completed** 2019-08-24 13:00 UTC
